Made 'user' optional and added sanity check for it when 'upload' is set to 'true'.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -81,7 +81,8 @@ inputs:
     default: false
   user:
     description: Name of the Anaconda user or organization where the conda package will be published.
-    required: true
+    required: false
+    dedault: ''
   label:
     description: Label of the published conda package.
     required: false
@@ -102,10 +103,16 @@ runs:
       shell: bash
       run: |
         echo "::group::Sanity checks on inputs"
-        if [ "${{ inputs.upload }}" == "true" ] && [ "${{ inputs.token }}" == "" ]; then
-           echo -e "An Anaconda token is required when the package is to be uploaded.\n"\
+        if [ "${{ inputs.upload }}" == "true" ]; then
+          if [ "${{ inputs.token }}" == "" ]; then
+            echo -e "An Anaconda token is required when the package is to be uploaded.\n"\
                     "Please specify a 'token', or set 'upload' to 'false'."
-           exit 1
+            exit 1
+          if [ "${{ inputs.user }}" == "" ]; then
+            echo -e "An Anaconda user or organization is required when the package is to be uploaded.\n"\
+                    "Please specify a 'user', or set 'upload' to 'false'."
+            exit 1
+          fi
         fi
         echo "::endgroup::"
     - name: Event trigger data
